export const bathroomData = [
  {
    id: "systemy-podtynkowe",
    title: "Systemy podtynkowe",
    brands: [
      {
        name: "Geberit",
        alt: "geberit",
        img: "/image/brands/geberit.png",
        url: "https://www.geberit.pl/",
        class: "bathroom-logo",
      },
      {
        name: "Werit",
        alt: "werit",
        img: "/image/brands/werit.png",
        url: "https://www.werit.eu/",
        class: "bathroom-logo",
      },
      {
        name: "Tece",
        alt: "tece",
        img: "/image/brands/tece.png",
        url: "https://www.tece.com/pl",
        class: "bathroom-logo",
      },
    ],
  },
  {
    id: "meble-lazienkowe",
    title: "Meble łazienkowe",
    brands: [
      {
        name: "Elita",
        alt: "elita",
        img: "/image/brands/elita.png",
        url: "https://www.elitameble.pl/",
        class: "bathroom-logo",
      },
      {
        name: "Roca",
        alt: "roca",
        img: "/image/brands/roca.png",
        url: "https://www.roca.pl/",
        class: "bathroom-logo",
      },
      {
        name: "Koło",
        alt: "kolo",
        img: "/image/brands/kolo.png",
        url: "https://www.kolo.com.pl/",
        class: "bathroom-logo",
      },
    ],
  },
  {
    id: "zlewozmywaki",
    title: "Zlewozmywaki",
    brands: [
      {
        name: "Ferro",
        alt: "Ferro",
        img: "/image/brands/ferro.png",
        url: "https://www.ferro.pl/",
        class: "bathroom-logo",
      },
      {
        name: "Franke",
        alt: "Franke",
        img: "/image/brands/franke.png",
        url: "https://www.franke.com/pl/pl/home.html",
        class: "bathroom-logo",
      },
      {
        name: "Deante",
        alt: "Deante",
        img: "/image/brands/deante.png",
        url: "https://deante.pl/",
        class: "bathroom-logo",
      },
    ],
  },
  {
    id: "ceramika",
    title: "Ceramika",
    brands: [
      {
        name: "Koło",
        alt: "kolo",
        img: "/image/brands/kolo.png",
        url: "https://www.kolo.com.pl/",
        class: "bathroom-logo",
      },
      {
        name: "Roca",
        alt: "roca",
        img: "/image/brands/roca.png",
        url: "https://www.roca.pl/",
        class: "bathroom-logo",
      },
    ],
  },
  {
    id: "odpływy-liniowe",
    title: "Odpływy liniowe",
    brands: [
      {
        name: "Uponor",
        alt: "uponor",
        img: "/image/brands/uponor.png",
        url: "https://www.uponor.com/en",
        class: "bathroom-logo",
      },
      {
        name: "Cedor",
        alt: "cedor",
        img: "/image/brands/cedor.png",
        url: "https://sklep-cedor.pl/",
        class: "bathroom-logo",
      },
      {
        name: "Ferro",
        alt: "Ferro",
        img: "/image/brands/ferro.png",
        url: "https://www.ferro.pl/",
        class: "bathroom-logo",
      },
      {
        name: "Werit",
        alt: "werit",
        img: "/image/brands/werit.png",
        url: "https://www.werit.eu/",
        class: "bathroom-logo",
      },
    ],
  },
  {
    id: "osprzet-lazienkowy",
    title: "Osprzęt łazienkowy",
    brands: [
      {
        name: "McAlpine",
        alt: "mcalpine",
        img: "/image/brands/mcalpine.png",
        url: "https://mcalpineplumbing.com/",
        class: "bathroom-logo",
      },
      {
        name: "Viega",
        alt: "viega",
        img: "/image/brands/viega.png",
        url: "https://www.viega.pl/",
        class: "bathroom-logo",
      },
    ],
  },
  {
    id: "wanny-i-kabiny",
    title: "Wanny i kabiny",
    brands: [
      {
        name: "Aquaform",
        alt: "aquaform",
        img: "/image/brands/aquaform.png",
        url: "http://www.aquaform.com.pl/",
        class: "bathroom-logo",
      },
      {
        name: "Koło",
        alt: "kolo",
        img: "/image/brands/kolo.png",
        url: "https://www.kolo.com.pl/",
        class: "bathroom-logo",
      },
      {
        name: "Radaway",
        alt: "radaway",
        img: "/image/brands/radaway.png",
        url: "https://www.radaway.pl/",
        class: "bathroom-logo",
      },
      {
        name: "Roca",
        alt: "roca",
        img: "/image/brands/roca.png",
        url: "https://www.roca.pl/",
        class: "bathroom-logo",
      },
      {
        name: "Sanplast",
        alt: "sanplast",
        img: "/image/brands/sanplast.png",
        url: "https://sanplast.pl/",
        class: "bathroom-logo",
      },
      {
        name: "SanSwiss",
        alt: "sanswiss",
        img: "/image/brands/sanswiss.png",
        url: "https://sanswiss.pl/",
        class: "bathroom-logo",
      },
    ],
  },
  {
    id: "osprzęt-łazienkowy",
    title: "Osprzęt łazienkowy",
    brands: [
      {
        name: "McAlpine",
        alt: "McAlpine",
        img: "/image/brands/mcalpine.png",
        url: "https://mcalpine.pl/",
        class: "bathroom-logo",
      },
      {
        name: "Viega",
        alt: "viega",
        img: "/image/brands/viega.png",
        url: "https://www.viega.pl/",
        class: "bathroom-logo",
      },
    ],
  },
];
