export const equipmentData = [
  {
    id: "zawory",
    title: "Zawory",
    brands: [
      {
        name: "Ferro",
        alt: "Ferro",
        img: "/image/brands/ferro.png",
        url: "https://www.ferro.pl/",
        class: "equipment-logo",
      },
      {
        name: "Caleffi",
        alt: "caleffi",
        img: "/image/brands/caleffi.png",
        url: "https://www.caleffi.com/",
        class: "equipment-logo",
      },
      {
        name: "Schlosser",
        alt: "schlosser",
        img: "/image/brands/schlosser.png",
        url: "https://www.schlosser.com.pl/",
        class: "equipment-logo",
      },
      {
        name: "Oventrop",
        alt: "oventrop",
        img: "/image/brands/oventrop.png",
        url: "https://www.oventrop.com/",
        class: "equipment-logo",
      },
      {
        name: "Herz",
        alt: "herz",
        img: "/image/brands/herz.png",
        url: "https://herz.com.pl/",
        class: "equipment-logo",
      },
      {
        name: "Schell",
        alt: "schell",
        img: "/image/brands/schell.png",
        url: "https://www.schell.eu/pl-pl/",
        class: "equipment-logo",
      },
    ],
  },
  {
    id: "armatura-equipment",
    title: "Armatura",
    brands: [
      {
        name: "Caleffi",
        alt: "caleffi",
        img: "/image/brands/caleffi.png",
        url: "https://www.caleffi.com/",
        class: "equipment-logo",
      },
      {
        name: "Ferro",
        alt: "Ferro",
        img: "/image/brands/ferro.png",
        url: "https://www.ferro.pl/",
        class: "equipment-logo",
      },
      {
        name: "Agaflex",
        alt: "agaflex",
        img: "/image/brands/agaflex.png",
        url: "https://www.agaflex.pl/",
        class: "equipment-logo",
      },
      {
        name: "Arco",
        alt: "arco",
        img: "/image/brands/arco.png",
        url: "https://valvulasarco.com/pl/",
        class: "equipment-logo",
      },
    ],
  },
  {
    id: "pompy-i-hydrofory",
    title: "Pompy i hydrofory",
    brands: [
      {
        name: "Pentair (Jung Pumpen)",
        alt: "pentair",
        img: "/image/brands/jungpumpenpentair.png",
        url: "https://www.jung-pumpen.com/",
        class: "equipment-logo",
      },
      {
        name: "LFP",
        alt: "lfp",
        img: "/image/brands/lfp.png",
        url: "https://www.lfp.com.pl/",
        class: "equipment-logo",
      },
      {
        name: "SFA",
        alt: "sfa",
        img: "/image/brands/sfa.png",
        url: "https://www.saniflo.com/",
        class: "equipment-logo",
      },
      {
        name: "Omnigena",
        alt: "omnigena",
        img: "/image/brands/omnigena.png",
        url: "https://omnigena.pl/",
        class: "equipment-logo",
      },
      {
        name: "Wilo",
        alt: "Wilo",
        img: "/image/brands/wilo.png",
        url: "https://www.wilo.pl/",
        class: "equipment-logo",
      },
    ],
  },
  {
    id: "sterowanie",
    title: "Sterowanie",
    brands: [
      {
        name: "Engo",
        alt: "Engo",
        img: "/image/brands/engo.png",
        url: "https://engocontrols.com/produkty/",
        class: "equipment-logo",
      },
      {
        name: "Euroster",
        alt: "euroster",
        img: "/image/brands/euroster.png",
        url: "https://euroster.com.pl/",
        class: "equipment-logo",
      },
      {
        name: "Salus",
        alt: "salus",
        img: "/image/brands/salus.png",
        url: "https://saluscontrols.com/pl/",
        class: "equipment-logo",
      },
      {
        name: "Tech",
        alt: "tech",
        img: "/image/brands/tech.png",
        url: "https://www.techsterowniki.pl/",
        class: "equipment-logo",
      },
    ],
  },
  {
    id: "skrzynka-gazowa",
    title: "Skrzynka gazowa",
    brands: [
      {
        name: "incobex",
        alt: "incobex",
        img: "/image/brands/incobex.png",
        url: "https://incobex.pl",
        class: "equipment-logo",
      },
      {
        name: "weba",
        alt: "weba",
        img: "/image/brands/weba.png",
        url: "https://weba.com.pl",
        class: "equipment-logo",
      },
    ],
  },
];
