export const heatingData = [
  {
    id: "gas-boilers",
    title: "KOTŁY GAZOWE",
    brands: [
      {
        name: "Junkers",
        alt: "Junkers",
        img: "/image/brands/junkers.png",
        url: "https://www.bosch-homecomfort.com/pl/pl/budynki-mieszkalne/informacje/aktualnosci/junkers-+-bosch-=-bosch-termotechnika/",
        class: "heating-logo",
      },
      {
        name: "Bosch",
        alt: "Bosch",
        img: "/image/brands/bosch.png",
        url: "https://www.bosch-homecomfort.com/pl/pl/budynki-mieszkalne/home/",
        class: "heating-logo",
      },
      {
        name: "Vaillant",
        alt: "Vaillant",
        img: "/image/brands/vaillant.png",
        url: "https://www.vaillant.pl/",
        class: "heating-logo",
      },
      {
        name: "Immergas",
        alt: "Immergas",
        img: "/image/brands/immergas.png",
        url: "https://www.immergas.pl/",
        class: "heating-logo",
      },
      {
        name: "Wolf",
        alt: "Wolf",
        img: "/image/brands/wolf.png",
        url: "https://www.wolf.eu/",
        class: "heating-logo",
      },
      {
        name: "Engo",
        alt: "Engo",
        img: "/image/brands/engo.png",
        url: "https://engocontrols.com/produkty/",
        class: "heating-logo",
      },
      {
        name: "Fondital",
        alt: "Fondital",
        img: "/image/brands/fondital.png",
        url: "https://www.fondital.com/pl/PL/",
        class: "heating-logo",
      },
      {
        name: "Viessmann",
        alt: "Viessmann",
        img: "/image/brands/viessmann.png",
        url: "https://www.viessmann.pl/",
        class: "heating-logo",
      },
      {
        name: "Buderus",
        alt: "Buderus",
        img: "/image/brands/buderus_bosch.png",
        url: "https://www.buderus.pl/",
        class: "heating-logo",
      },
      {
        name: "De Dietrich",
        alt: "De Dietrich",
        img: "/image/brands/dedietrich.png",
        url: "https://www.dedietrich.pl/",
        class: "heating-logo",
      },
      {
        name: "Termet",
        alt: "Termet",
        img: "/image/brands/termet.png",
        url: "https://www.termet.com.pl/",
        class: "heating-logo",
      },
      {
        name: "Atlantic",
        alt: "Atlantic",
        img: "/image/brands/atlantic.png",
        url: "https://groupe-atlantic.pl/",
        class: "heating-logo",
      },
    ],
  },
  {
    id: "kotly-stalopalne",
    title: "KOTŁY stałopalne",
    brands: [
      {
        name: "Engo",
        alt: "Engo",
        img: "/image/brands/engo.png",
        url: "https://engocontrols.com/produkty/",
        class: "heating-logo",
      },
      {
        name: "Defro",
        alt: "Defro",
        img: "/image/brands/defro.png",
        url: "https://www.defro.pl/",
        class: "heating-logo",
      },
      {
        name: "Klimosz",
        alt: "Klimosz",
        img: "/image/brands/klimosz.png",
        url: "https://www.klimosz.pl/",
        class: "heating-logo",
      },
      {
        name: "SAS",
        alt: "SAS",
        img: "/image/brands/sas.png",
        url: "https://www.sas.busko.pl/",
        class: "heating-logo",
      },
      {
        name: "Ogniwo",
        alt: "Ogniwo",
        img: "/image/brands/ogniwo.png",
        url: "http://www.ogniwobiecz.pl/",
        class: "heating-logo",
      },
      {
        name: "Stalmark",
        alt: "Stalmark",
        img: "/image/brands/stalmark.png",
        url: "https://www.stalmark.pl/",
        class: "heating-logo",
      },
      {
        name: "Tekla",
        alt: "Tekla",
        img: "/image/brands/tekla.png",
        url: "https://www.teklakotly.pl/",
        class: "heating-logo",
      },
      {
        name: "Viessmann",
        alt: "Viessmann",
        img: "/image/brands/viessmann.png",
        url: "https://www.viessmann.pl/",
        class: "heating-logo",
      },
      {
        name: "Heiztechnik",
        alt: "Heiztechnik",
        img: "/image/brands/heiztechnik.png",
        url: "https://www.heiztechnik.pl/",
        class: "heating-logo",
      },
      {
        name: "Elektromet",
        alt: "Elektromet",
        img: "/image/brands/elektromet.png",
        url: "https://www.elektromet.com.pl/",
        class: "heating-logo",
      },
    ],
  },
  {
    id: "kotly-inne",
    title: "KOTŁY INNE",
    brands: [
      {
        name: "Buderus",
        alt: "Buderus",
        img: "/image/brands/buderus_bosch.png",
        url: "https://www.buderus.pl/",
        class: "heating-logo",
      },
      {
        name: "Kospel",
        alt: "Kospel",
        img: "/image/brands/kospel.png",
        url: "https://www.kospel.pl/",
        class: "heating-logo",
      },
      {
        name: "Vaillant",
        alt: "Vaillant",
        img: "/image/brands/vaillant.png",
        url: "https://www.vaillant.pl/",
        class: "heating-logo",
      },
      {
        name: "Engo",
        alt: "Engo",
        img: "/image/brands/engo.png",
        url: "https://engocontrols.com/produkty/",
        class: "heating-logo",
      },
      {
        name: "De Dietrich",
        alt: "De Dietrich",
        img: "/image/brands/dedietrich.png",
        url: "https://www.dedietrich.pl/",
        class: "heating-logo",
      },
      {
        name: "Viessmann",
        alt: "Viessmann",
        img: "/image/brands/viessmann.png",
        url: "https://www.viessmann.pl/",
        class: "heating-logo",
      },
      {
        name: "Atlantic",
        alt: "Atlantic",
        img: "/image/brands/atlantic.png",
        url: "https://groupe-atlantic.pl/",
        class: "heating-logo",
      },
    ],
  },
  {
    id: "grzejniki",
    title: "Grzejniki",
    brands: [
      {
        name: "Brugman",
        alt: "Brugman",
        img: "/image/brands/brugman.png",
        url: "https://www.brugman.pl/",
        class: "heating-logo",
      },
      {
        name: "Vasco",
        alt: "Vasco",
        img: "/image/brands/vasco.png",
        url: "https://vasco.eu/",
        class: "heating-logo",
      },
      {
        name: "Engo",
        alt: "Engo",
        img: "/image/brands/engo.png",
        url: "https://engocontrols.com/produkty/",
        class: "heating-logo",
      },
      {
        name: "Gorgiel",
        alt: "Gorgiel",
        img: "/image/brands/gorgiel.png",
        url: "https://gorgiel.pl/",
        class: "heating-logo",
      },
      {
        name: "Fondital",
        alt: "Fondital",
        img: "/image/brands/fondital.png",
        url: "https://www.fondital.com/pl/PL/",
        class: "heating-logo",
      },
      {
        name: "Instal-Projekt",
        alt: "Instal-Projekt",
        img: "/image/brands/instal_projekt.png",
        url: "https://www.instalprojekt.com.pl/",
        class: "heating-logo",
      },
      {
        name: "Kermi",
        alt: "Kermi",
        img: "/image/brands/kermi.png",
        url: "https://www.kermi.com/",
        class: "heating-logo",
      },
      {
        name: "Luxor Koronowo",
        alt: "Luxor Koronowo",
        img: "/image/brands/luxor_koronowo.png",
        url: "https://luxor2.pl/",
        class: "heating-logo",
      },
      {
        name: "Atlantic",
        alt: "Atlantic",
        img: "/image/brands/atlantic.png",
        url: "https://groupe-atlantic.pl/",
        class: "heating-logo",
      },
      {
        name: "Enix",
        alt: "Enix",
        img: "/image/brands/enix.png",
        url: "https://www.enix.pl/",
        class: "heating-logo",
      },
    ],
  },
  {
    id: "pompy-ciepla",
    title: "POMPY CIEPŁA",
    brands: [
      {
        name: "Engo",
        alt: "Engo",
        img: "/image/brands/engo.png",
        url: "https://engocontrols.com/produkty/",
        class: "heating-logo",
      },
      {
        name: "Reflex",
        alt: "Reflex",
        img: "/image/brands/reflex.png",
        url: "https://reflex-winkelmann.com/pl",
        class: "heating-logo",
      },
      {
        name: "Kospel",
        alt: "Kospel",
        img: "/image/brands/kospel.png",
        url: "https://www.kospel.pl/",
        class: "heating-logo",
      },
      {
        name: "Vaillant",
        alt: "Vaillant",
        img: "/image/brands/vaillant.png",
        url: "https://www.vaillant.pl/",
        class: "heating-logo",
      },
      {
        name: "Atlantic",
        alt: "Atlantic",
        img: "/image/brands/atlantic.png",
        url: "https://groupe-atlantic.pl/",
        class: "heating-logo",
      },
      {
        name: "Panasonic",
        alt: "Panasonic",
        img: "/image/brands/panasonic.png",
        url: "https://www.aircon.panasonic.eu/PL_pl/",
        class: "heating-logo",
      },
      {
        name: "Stiebel Eltron",
        alt: "Stiebel Eltron",
        img: "/image/brands/stiebel.png",
        url: "https://www.stiebel-eltron.pl/",
        class: "heating-logo",
      },
      {
        name: "De Dietrich",
        alt: "De Dietrich",
        img: "/image/brands/dedietrich.png",
        url: "https://www.dedietrich.pl/",
        class: "heating-logo",
      },
    ],
  },
  {
    id: "izolacje",
    title: "IZOLACJE",
    brands: [
      {
        name: "Thermaflex",
        alt: "Thermaflex",
        img: "/image/brands/thermaflex.png",
        url: "https://www.thermaflex.com/pl/",
        class: "heating-logo",
      },
    ],
  },
  {
    id: "rekuperacja",
    title: "REKUPERACJA",
    brands: [
      {
        name: "Engo",
        alt: "Engo",
        img: "/image/brands/engo.png",
        url: "https://engocontrols.com/produkty/",
        class: "heating-logo",
      },
      {
        name: "Heatpex",
        alt: "Heatpex",
        img: "/image/brands/heatpex.png",
        url: "https://heatpex.pl/",
        class: "heating-logo",
      },
      {
        name: "Vasco",
        alt: "Vasco",
        img: "/image/brands/vasco.png",
        url: "https://vasco.eu/",
        class: "heating-logo",
      },
      {
        name: "Vaillant",
        alt: "Vaillant",
        img: "/image/brands/vaillant.png",
        url: "https://www.vaillant.pl/",
        class: "heating-logo",
      },
      {
        name: "ova-system",
        alt: "ova-system",
        img: "/image/brands/ova-system.png",
        url: "https://www.ova-system.pl/",
        class: "heating-logo",
      },
    ],
  },
  {
    id: "systemy-narzedziowe",
    title: "SYSTEMY NARZĘDZIOWE",
    brands: [
      {
        name: "Logo Tools",
        alt: "Logo Tools",
        img: "/image/brands/logo-tools.png",
        url: "https://www.logo-tools.pl/",
        class: "heating-logo",
      },
      {
        name: "Rothenberger",
        alt: "Rothenberger",
        img: "/image/brands/rothenberger.png",
        url: "https://rothenberger.com/pl-pl/",
        class: "heating-logo",
      },
    ],
  },
  {
    id: "systemy-solarne",
    title: "SYSTEMY SOLARNE",
    brands: [
      {
        name: "Engo",
        alt: "Engo",
        img: "/image/brands/engo.png",
        url: "https://engocontrols.com/produkty/",
        class: "heating-logo",
      },
      {
        name: "Biawar",
        alt: "Biawar",
        img: "/image/brands/biawar.png",
        url: "https://www.biawar.com.pl/",
        class: "heating-logo",
      },
      {
        name: "Kospel",
        alt: "Kospel",
        img: "/image/brands/kospel.png",
        url: "https://www.kospel.pl/",
        class: "heating-logo",
      },
      {
        name: "Viessmann",
        alt: "Viessmann",
        img: "/image/brands/viessmann.png",
        url: "https://www.viessmann.pl/",
        class: "heating-logo",
      },
      {
        name: "Vaillant",
        alt: "Vaillant",
        img: "/image/brands/vaillant.png",
        url: "https://www.vaillant.pl/",
        class: "heating-logo",
      },
    ],
  },
  {
    id: "pompy",
    title: "Pompy",
    brands: [
      {
        name: "Wilo",
        alt: "Wilo",
        img: "/image/brands/wilo.png",
        url: "https://www.wilo.pl/",
        class: "heating-logo",
      },
      {
        name: "Engo",
        alt: "Engo",
        img: "/image/brands/engo.png",
        url: "https://engocontrols.com/produkty/",
        class: "heating-logo",
      },
      {
        name: "Ferro",
        alt: "Ferro",
        img: "/image/brands/ferro.png",
        url: "https://www.ferro.pl/",
        class: "heating-logo",
      },
      {
        name: "LFP",
        alt: "lfp",
        img: "/image/brands/lfp.png",
        url: "https://www.lfp.com.pl/",
        class: "heating-logo",
      },
      {
        name: "Grundfos",
        alt: "grundfos",
        img: "/image/brands/grundfos.png",
        url: "https://www.grundfos.com/pl/",
        class: "heating-logo",
      },
    ],
  },
  {
    id: "chimneys",
    title: "Kominy",
    brands: [
      {
        name: "Engo",
        alt: "Engo",
        img: "/image/brands/engo.png",
        url: "https://engocontrols.com/produkty/",
        class: "heating-logo",
      },
      {
        name: "Ekon",
        alt: "ekon",
        img: "/image/heating/ekon.png",
        url: "https://www.ekon.com.pl/",
        class: "heating-logo",
      },
      {
        name: "MK Żary",
        alt: "mk_zary",
        img: "/image/heating/mk_zary.png",
        url: "https://www.mkzary.pl/",
        class: "heating-logo",
      },
    ],
  },
];
