export const plumbingData = [
  {
    id: "instalacje",
    title: "Instalacje",
    brands: [
      {
        name: "VesboPoland",
        alt: "VesboPoland",
        img: "/image/brands/vesbopoland.png",
        url: "https://www.vesbopoland.pl",
        class: "plumbing-logo",
      },
      {
        name: "Engo",
        alt: "Engo",
        img: "/image/brands/engo.png",
        url: "https://engocontrols.com/produkty/",
        class: "plumbing-logo",
      },
      {
        name: "MagnaPlast",
        alt: "magna",
        img: "/image/brands/magna.png",
        url: "https://www.magnaplast.pl/",
        class: "plumbing-logo",
      },
      {
        name: "Arco",
        alt: "Arco",
        img: "/image/brands/arco.png",
        url: "https://valvulasarco.com/pl/",
        class: "plumbing-logo",
      },
      {
        name: "PacoFlex",
        alt: "PacoFlex",
        img: "/image/brands/pacoflex.png",
        url: "https://pacoflex.pl",
        class: "plumbing-logo",
      },
    ],
  },
  {
    id: "armatura",
    title: "Armatura",
    brands: [
      {
        name: "PacoFlex",
        alt: "PacoFlex",
        img: "/image/brands/pacoflex.png",
        url: "https://pacoflex.pl",
        class: "plumbing-logo",
      },
      {
        name: "Afriso",
        alt: "afriso",
        img: "/image/brands/afriso.png",
        url: "https://www.afriso.pl/",
        class: "plumbing-logo",
      },
      {
        name: "Caleffi",
        alt: "caleffi",
        img: "/image/brands/caleffi.png",
        url: "https://www.caleffi.com/",
        class: "plumbing-logo",
      },
      {
        name: "Oventrop",
        alt: "oventrop",
        img: "/image/brands/oventrop.png",
        url: "https://www.oventrop.com/",
        class: "plumbing-logo",
      },
      {
        name: "Herz",
        alt: "herz",
        img: "/image/brands/herz.png",
        url: "https://herz.com.pl/",
        class: "plumbing-logo",
      },
      {
        name: "Meibes",
        alt: "meibes",
        img: "/image/brands/meibes.png",
        url: "https://flamco.aalberts-hfc.com/pl",
        class: "plumbing-logo",
      },
      {
        name: "Ferro",
        alt: "Ferro",
        img: "/image/brands/ferro.png",
        url: "https://www.ferro.pl/",
        class: "plumbing-logo",
      },
    ],
  },
  {
    id: "instalacje-miedzowe",
    title: "Instalacje miedzowe",
    brands: [
      {
        name: "Hutmen",
        alt: "hutmen",
        img: "/image/brands/hutmen.png",
        url: "https://hutmen.polfirms.eu/",
        class: "plumbing-logo",
      },
      {
        name: "PacoFlex",
        alt: "PacoFlex",
        img: "/image/brands/pacoflex.png",
        url: "https://pacoflex.pl",
        class: "plumbing-logo",
      },
      {
        name: "Sanha",
        alt: "sanha",
        img: "/image/brands/sanha.png",
        url: "https://www.sanha.com/",
        class: "plumbing-logo",
      },
      {
        name: "Viega",
        alt: "viega",
        img: "/image/brands/viega.png",
        url: "https://www.viega.pl/",
        class: "plumbing-logo",
      },
    ],
  },
  {
    id: "instalacje-gwintowane",
    title: "Instalacje gwintowane",
    brands: [
      {
        name: "Arco",
        alt: "Arco",
        img: "/image/brands/arco.png",
        url: "https://valvulasarco.com/pl/",
        class: "plumbing-logo",
      },
      {
        name: "PacoFlex",
        alt: "PacoFlex",
        img: "/image/brands/pacoflex.png",
        url: "https://pacoflex.pl",
        class: "plumbing-logo",
      },
      {
        name: "Ferro",
        alt: "Ferro",
        img: "/image/brands/ferro.png",
        url: "https://www.ferro.pl/",
        class: "plumbing-logo",
      },
      {
        name: "Agaflex",
        alt: "agaflex",
        img: "/image/brands/agaflex.png",
        url: "https://www.agaflex.pl/",
        class: "plumbing-logo",
      },
    ],
  },
  {
    id: "oczyszczalnie",
    title: "Oczyszczalnie",
    brands: [
      {
        name: "Delfin",
        alt: "delfin",
        img: "/image/brands/delfin.png",
        url: "https://www.delfin-polska.pl/",
        class: "plumbing-logo",
      },
      {
        name: "klarwod",
        alt: "klarwod",
        img: "/image/brands/klarwod.png",
        url: "https://www.klarwod.pl/",
        class: "plumbing-logo",
      },
    ],
  },
  {
    id: "systemy-pex",
    title: "Systemy PEX",
    brands: [
      {
        name: "PacoFlex",
        alt: "PacoFlex",
        img: "/image/brands/pacoflex.png",
        url: "https://pacoflex.pl",
        class: "plumbing-logo",
      },
      {
        name: "Tweetop",
        alt: "tweetop",
        img: "/image/brands/tweetop.png",
        url: "https://www.tweetop.pl/",
        class: "plumbing-logo",
      },
      {
        name: "VesboPoland",
        alt: "VesboPoland",
        img: "/image/brands/vesbopoland.png",
        url: "https://www.vesbopoland.pl",
        class: "plumbing-logo",
      },
      {
        name: "Herz",
        alt: "herz",
        img: "/image/brands/herz.png",
        url: "https://herz.com.pl/",
        class: "plumbing-logo",
      },
    ],
  },
  {
    id: "instalacje-stalowe",
    title: "Instalacje stalowe",
    brands: [
      {
        name: "PacoFlex",
        alt: "PacoFlex",
        img: "/image/brands/pacoflex.png",
        url: "https://pacoflex.pl",
        class: "plumbing-logo",
      },
      {
        name: "VesboPoland",
        alt: "VesboPoland",
        img: "/image/brands/vesbopoland.png",
        url: "https://www.vesbopoland.pl",
        class: "plumbing-logo",
      },
      {
        name: "Sanha",
        alt: "sanha",
        img: "/image/brands/sanha.png",
        url: "https://www.sanha.com/",
        class: "plumbing-logo",
      },
    ],
  },
  {
    id: "systemy-mocujace",
    title: "Systemy mocujące",
    brands: [
      {
        name: "PacoFlex",
        alt: "PacoFlex",
        img: "/image/brands/pacoflex.png",
        url: "https://pacoflex.pl",
        class: "plumbing-logo",
      },
      {
        name: "Gorgiel",
        alt: "gorgiel",
        img: "/image/brands/gorgiel.png",
        url: "https://gorgiel.pl/",
        class: "plumbing-logo",
      },
    ],
  },
  {
    id: "systemy-zgrzewane",
    title: "Systemy zgrzewane",
    class: "welded-systems",
    brands: [
      {
        name: "Sigmali",
        alt: "sigmali",
        img: "/image/brands/sigmali.png",
        url: "https://www.sigmali.pl/",
        class: "plumbing-logo",
      },
    ],
  },
  {
    id: "systemy-zaprasowywane",
    title: "Systemy zaprasowywane",
    brands: [
      {
        name: "PacoFlex",
        alt: "PacoFlex",
        img: "/image/brands/pacoflex.png",
        url: "https://pacoflex.pl",
        class: "plumbing-logo",
      },
      {
        name: "Geberit",
        alt: "geberit",
        img: "/image/brands/geberit.png",
        url: "https://www.geberit.pl/",
        class: "plumbing-logo",
      },
      {
        name: "Kisan",
        alt: "kisan",
        img: "/image/brands/kisan.png",
        url: "https://www.kisan.pl/",
        class: "plumbing-logo",
      },
      {
        name: "Sanha",
        alt: "sanha",
        img: "/image/brands/sanha.png",
        url: "https://www.sanha.com/",
        class: "plumbing-logo",
      },
      {
        name: "Viega",
        alt: "viega",
        img: "/image/brands/viega.png",
        url: "https://www.viega.pl/",
        class: "plumbing-logo",
      },
    ],
  },
];
